/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package srt;

/**
 *
 * @author SuperUs
 */
public class crt extends javax.swing.JFrame {
    String EMPTY = new String ();
    String Mensaje = "  ";
    int a=0,b=0,c=0,d=0,e=0,f=0;
    int cu;
    int numPro=1;

    /**
     * Creates new form crt
     */
    public crt() {
        
       
        jTextFieldB.setVisible(false);
        jTextFieldC.setVisible(false);
        jTextFieldD.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
    
    
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabeltitulo2 = new javax.swing.JLabel();
        jLabelNC = new javax.swing.JLabel();
        jTextFieldCuan = new javax.swing.JTextField();
        jTextFieldA = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldB = new javax.swing.JTextField();
        jTextFieldC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldD = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabeltitulo2.setFont(new java.awt.Font("Castellar", 0, 36)); // NOI18N
        jLabeltitulo2.setText("SRT");
        getContentPane().add(jLabeltitulo2);
        jLabeltitulo2.setBounds(270, 20, 100, 60);

        jLabelNC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNC.setText("CUANTUM");
        getContentPane().add(jLabelNC);
        jLabelNC.setBounds(303, 90, 90, 30);

        jTextFieldCuan.setBackground(new java.awt.Color(102, 255, 255));
        jTextFieldCuan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextFieldCuan);
        jTextFieldCuan.setBounds(433, 90, 90, 30);

        jTextFieldA.setBackground(new java.awt.Color(102, 255, 255));
        jTextFieldA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextFieldA);
        jTextFieldA.setBounds(433, 130, 90, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("De cuanto va a ser el proceso A?");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(133, 130, 270, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("De cuanto va a ser el proceso B?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(133, 170, 260, 30);

        jTextFieldB.setBackground(new java.awt.Color(102, 255, 255));
        jTextFieldB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextFieldB);
        jTextFieldB.setBounds(433, 170, 90, 30);

        jTextFieldC.setBackground(new java.awt.Color(102, 255, 255));
        jTextFieldC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextFieldC);
        jTextFieldC.setBounds(433, 210, 90, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("De cuanto va a ser el proceso C?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(133, 210, 260, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("De cuanto va a ser el proceso D?");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(133, 250, 270, 30);

        jTextFieldD.setBackground(new java.awt.Color(102, 255, 255));
        jTextFieldD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextFieldD);
        jTextFieldD.setBounds(433, 250, 90, 30);

        jButton2.setBackground(new java.awt.Color(0, 51, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 255));
        jButton2.setText("AGREGAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(173, 340, 140, 40);

        jButton1.setBackground(new java.awt.Color(0, 51, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 255));
        jButton1.setText("ENVIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(363, 340, 160, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        numPro=numPro+1;
        if(numPro==2){
            jLabel2.setVisible(true);
            jTextFieldB.setVisible(true);}
        if(numPro==3){
            jLabel3.setVisible(true);
            jTextFieldC.setVisible(true);}
        if(numPro==4){
            jLabel4.setVisible(true);
            jTextFieldD.setVisible(true);}
        //if(numPro==5){
            //  jLabel5.setVisible(true);
            //jTextFieldE.setVisible(true);}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println("num"+numPro);
        if(numPro==1){
            a=Integer.parseInt(jTextFieldA.getText());
            cu=Integer.parseInt(jTextFieldCuan.getText());
        }
        else if(numPro==2){
            a=Integer.parseInt(jTextFieldA.getText());
            b=Integer.parseInt(jTextFieldB.getText());
            cu=Integer.parseInt(jTextFieldCuan.getText());
        }
        else if(numPro==3){
            a=Integer.parseInt(jTextFieldA.getText());
            b=Integer.parseInt(jTextFieldB.getText());
            c=Integer.parseInt(jTextFieldC.getText());
            cu=Integer.parseInt(jTextFieldCuan.getText());
        }
        else if(numPro==4){
            a=Integer.parseInt(jTextFieldA.getText());
            b=Integer.parseInt(jTextFieldB.getText());
            c=Integer.parseInt(jTextFieldC.getText());
            d=Integer.parseInt(jTextFieldD.getText());
            cu=Integer.parseInt(jTextFieldCuan.getText());
        }

        //if((jTextFieldA.getText().equals(EMPTY))||(jTextFieldB.getText().equals(EMPTY))||(jTextFieldC.getText().equals(EMPTY))||(jTextFieldD.getText().equals(EMPTY))||(jTextFieldCuan.getText().equals(EMPTY)))
        //  Mensaje= "Campos en Blanco";

        // else{
            System.out.println("d"+d);
            crt_p abrirventana= new crt_p(a,b,c,d,cu,numPro);
            //Robin abrirventana= new Robin();
            abrirventana.setVisible(true);
            //}
        //lMensaje.setText(Mensaje);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelNC;
    private javax.swing.JLabel jLabeltitulo2;
    private javax.swing.JTextField jTextFieldA;
    private javax.swing.JTextField jTextFieldB;
    private javax.swing.JTextField jTextFieldC;
    private javax.swing.JTextField jTextFieldCuan;
    private javax.swing.JTextField jTextFieldD;
    // End of variables declaration//GEN-END:variables
}
